feishu_webhook:
  group: https://open.feishu.cn/open-apis/bot/v2/hook/0d42a3a8-13b9-4942-9760-ba71ec9ab02a
  test: https://open.feishu.cn/open-apis/bot/v2/hook/aaf1ee85-6656-4870-92ec-2378352c5a03

openai:
  api_key: diaohan.ai_news_robot
  base_url: https://openai-proxy.diandian.info/v1
  model: gpt-4o-08-06

serper:
  api_key: 722e573335acce5a4df8f73837c82eca4f67eafe
  base_url: https://scrape.serper.dev

schedule:
  time: "09:55"
